var:
  url-repo: https://github.com/LeCoinStat/Cours-de-Python   # to call this value : {{< meta var.url-repo >}}

project:
  type: website

website:
  title: "Base de données"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#447099"
    left:
      - icon: house
        href: index.qmd
        text: Home
      - text: Cours
        menu:
          - href: doc/cours/intro.qmd
            text: "Présentation du cours"
          - href: doc/cours/introduction.qmd
            text: "Les Fondamentaux de Python : Variables, Structures et Conditions"
          - href: doc/cours/typedonnees.qmd
            text: "Les types de données en Python"
     
      - text: TP
        menu:
          - href: doc/tp/tp1.qmd
            text: "TP1 - Premières requêtes"
    right:
      - href: doc/glossaire.qmd
        text: Glossaire
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Code source]({{< meta var.url-repo >}}){.external target="_blank"}

execute:
  freeze: auto  # re-render only when source changes

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
  revealjs: 
    css: styles-reveal.css
